### ISSUE TITLE
going to release 1.1 any time soon?

### ISSUE THREAD

**Issue by scphantm** [WASdev/ci.gradle#103]
Seems you have been working on 1.1 for a year now.  The fact that this is snapshot means i can't deploy it to production in my environment.  (corp rules).  planning a release any time soon?

**Comment by cthigh** [comment]
You are right that the last release was about a year ago.  We have been actively working on a new release of the Gradle plugin this quarter with lots of new enhancements going into the latest snapshots. I don't have the release date but soon.

**Comment by cthigh** [comment]
Version 2.0 was released today!
