### ISSUE TITLE
Implement incremental build annotations

### ISSUE THREAD

**Issue by scphantm** [WASdev/ci.gradle#105]
my company won't let me contribute to this, but you could ease fears and add value by implementing incremental builds.  for example, task `installLiberty`

currently, every time you do something `installLiberty` is run.  But, since there are no incremental builds setup, you never really know if it did anything or not.  The log just shows that it ran.  So the user asks the question, "did it install anything?", "does it really reinstall on every run?"

if you were to add something like this to the task

```
class InstallLibertyTask {
@Input
String license

@Input
String downloadurl

  @OutputDirectory
  File folderToInstallLibertyIn

def InstallLibertyTask(){
folderToInstallLibertyIn = project.wherever.this.value.is.in.extension.
downloadurl= project.wherever.this.value.is.in.extension
license=project.wherever.this.value.is.in.extension
}
}
```

what would happen is gradle would look to see if any of those annotated values changed since the last time it ran.  if it didn't detect a change, then you would get

`:installLiberty UP-TO-DATE`

in your log.  this tells the user that it just checked the install but didn't actually install anything.  it also makes the build much faster because gradle will skip the step if it feels that everything is up to date.

I would make the change, but my company doesn't allow it and i would run into major legal issues.

**Comment by cthigh** [comment]
We were looking at incremental builds more for this release, but there are some issues. Without inclremental build, the underlying Ant task displays some messages that indicate if the install was done or if the runtime was already installed, but you don't see those without more info requested. To support incremental builds for installLiberty, we would need to also remove or clean the build if the inputs change. For now, the Ant task checks to see if the build is already installed, and if you want to change the build installLiberty inputs, you have to clean or remove the runtime.

**Comment by dshimo** [comment]
If the user is curious what `installLiberty` does every run, the user can add a `-i` or `--info` flag to see a verbose version of the task. Ant's info messages in `installLiberty` is usually:
`Liberty profile is already installed`.   
  
If we want to have Gradle's `UP-TO-DATE` message, we can, for example, set the `wlp` directory be `installLiberty`'s output. This speeds up the build by 0.014 seconds by bypassing the check built into the Ant task. Analyzing optimal inputs would take more time, but this investigation may be worth it if requested.

**Comment by scphantm** [comment]
The problem is the rank and file aren't going to know about the -i.  All they are going to see is gradle looking at them stupidly for several minutes, assume its locked up, kill the window and submit a support ticket.  i manage 1800 developers, 1000 overseas, i know how lazy they are and their habits.  and for us, a support ticket costs $18.50 to process and a one day turnaround.  

I've been thru this with other systems we have tried to implement, i know what will happen.  

All im saying for you is to be descriptive of what is happening.  People expect the incremental build system nowadays, its only been out for 2 years or so.  rank and file users really don't care if the ant build fires or any of that.  all they care about is their procedure says run `./gradlew build`.  if it doesn't work, file a ticket.

keep in mind also, only about 1/2 to 1/3 of my users are actual developers.  the rest are BA's and other testers.

**Comment by cthigh** [comment]
Thank for the feedback. I think replacing the install without a clean in something we should consider for a future release.  When we handle that, incremental install support will go along.
