### ISSUE TITLE
Be more descriptive about whats going on

### ISSUE THREAD

**Issue by scphantm** [WASdev/ci.gradle#106]
I just had one of my testers call me up about this.  The liberty distro that we are using with the plugin uses `runtimeUrl` and pulls the file out of our artifactory server.  Its 160 megs and takes a while to get to the desktop.  I had a tester kill the build 3 times before they realized that it wasn't hung, it was just downloading the file.  Add additional `project.logger.lifecycle()` statements to tell the user whats going on, if its downloading something, then tell them.  possibly dump a status bar to the screen or something.  The more you tell users, the less support calls I get and support calls = money.

**Comment by hughesj** [comment]
Do you mean something similar to: https://github.com/michel-kraemer/gradle-download-task

**Comment by scphantm** [comment]
yes, exactly.  my testers are getting hung up when the thing just sits there and doesn't tell them whats going on.  if the dev is over the vpn, that file could take several minutes to download.  the testers are thinking the build is hung because its not communicating anything and kill it, not knowing that its actually downloading a file in the background.

this would solve that.

**Comment by cthigh** [comment]
Version 2.0 of the plugin updates installLiberty to allow you to install using a dependency to Maven Central or your artifactory server. Configure it using the `libertyRuntime` dependency.

dependencies {
    libertyRuntime group: 'com.ibm.websphere.appserver.runtime', name: 'wlp-webProfile7', version: '17.0.0.2'
}

When you download a dependency, you will get the progress indicator automatically.
![image](https://user-images.githubusercontent.com/17861985/31581235-fdc33908-b12b-11e7-8ef5-24350ad56dad.png)
