### ISSUE TITLE
use Gradle configurations for deployment

### ISSUE THREAD

**Issue by scphantm** [WASdev/ci.gradle#122]
for the deploy task, why are you requiring people to specify files?  Files change, all the time.  names change, locations change, etc.  Why don't you make a more iron clad way

```
configurations{
  libertyDeploy
}

dependencies {
  libertyDeploy project(":app-war")
}
```

that way a subproject can be automatically deployed.  no need to figure out how in the world to extract the file name from one subproject to another.  This is a much more reliable way.  Not only that, this will also add an implicit dependsOn that will fire the :app-war:war task every time you do a deployment automatically.

Its just a much more "gradle" way of doing things.  the approach thats built in right now has a very "ant" feel to it.

**Comment by cthigh** [comment]
Hi @scphantm, the 2.0 version of the plugin introduces installApps.  You can configure installApps to install given a war task or a file. This task copies the files rather than using the ant task to deploy. We introduced an `apps` and `dropins` configuration for the server.  Not exactly what you are asking for here, but check that out and let us know how we can improve it.

https://github.com/WASdev/ci.gradle/blob/master/docs/installApps.md

**Comment by scphantm** [comment]
I actually forked the project internally and rewrote big swaths of it.  I had no choice because the way you wrote things (using an ant style) just wasnt compatible with other systems we have internally that expect gradle plugins to act like gradle plugins, not ant plugins.  I got the OK from legal to submit it back as a 2.1, im meeting with my VP in a week or two to try to get him to sign away the intellectual property rights so i can submit it back to you as a 2.1.  

The changes i made are as such:

1. Liberty is now a language as far as gradle is concerned.  I implemented the directory structure into a sourceset, that way you can configure the locations of the source files and nothing is officially hard coded.  This was important because our seed tasks that build out the projects (gradlew seed) work off sourcesets.  so the way you had it with the hard coded paths, the seed task had no idea what folder structure to create
2. Extending on the sourceset system, i implemented the main configuration files (your copyconfig method in the abstractservertask class) into individual tasks in gradle.   the problem we had was if you changed one of the files, you had to completely rebuild the liberty install for liberty to pick it up.  that made no sense to us.  so making each file its own individual configuration task means that gradle can deploy the file if things changed, then restart liberty, instead of rebuilding the install.  This by far took the longest, but it turned out really nice
3. I implemented this deploy by configuration, it was pretty rudimentary with the other changes i made.  You can now define a project as a dependency to the libertyDeploy configuration.  then when you run the deploy task, gradle will resolve the deployment into a war file and then call the ant task to deploy it.  Its super simple to do and the best part is it implements the gradle workflow.  which means if you have a multi project system, doing a deploy will also trigger any build on the war or ear file.  
4. I completely rebuilt the liberty.groovy file.  that thing is a mess, i cleaned it up, made groovy a bit happier.  I also rebuilt the task workflows.  things now operate as you would expect, things like it wont try to start the server if its already running, or stop the server if its already stopped.  that stuff was driving us nuts, its fixed now.

like i said, i am desperately trying to push this stuff back to you.  but it will take a few weeks to get the approvals.  I think you will like what you see tho, the damn thing actually acts like a gradle plugin now, not an ant wrapper.  This makes integration SO much easier on large gradle based systems

The way my push will work when done is i will open a merge request and put everything there.  I have written no tests yet because the changes i have to make to the build file to work from our firewall are substantial and i cant run the tests at all internally, they all fail because they cant download stuff.  I highly recommend you configure this project to run a travisCI job.  That way the tests will run after each commit.  take a look at https://github.com/linkedin/pygradle  I contribute to that and they have one hell of a travisci configuration.  that way we can run the test.  But im probably going to need your guys help writing them.  once the tests are good and we agree, i will finish it off by updating the documentation and you can release as a 2.5 or 3.0 or whatever you want.  

like i said, give me a few weeks, im trying and so far everyone agrees i can submit it back, i just need the paperwork done.

**Comment by scphantm** [comment]
oh, and i would really like to implement a codenarc scan on this.  the groovy code is a mess, following the codenarc ruleset we adopted from LinkedIn is a REALLY good thing, when you go compliant, the code is so much better quality.  We are implementing it enterprise wide in our shop and its paying off big time.  But that will be a big change, will probably be best to do that as a different merge request after this first one is complete.

**Comment by cthigh** [comment]
Looking forward to seeing your PR and suggestions.
