### ISSUE TITLE
plugin fails as submodule with single build.gradle

### ISSUE THREAD

**Issue by scphantm** [WASdev/ci.gradle#137]
i think this is a gradle issue, but im putting it out here as well because im stuck and out of ideas

https://discuss.gradle.org/t/buildscript-classpath-in-multi-project-project/24535

does anyone know why this fails if you use a single build file in a multi-build project?

**Comment by cthigh** [comment]
Looks like you solved this with

```
BTW, i figured this out. I had to change all the
classpath: project.buildscript.configurations.classpath.asPath)

with

classpath: project.rootproject.buildscript.configurations.classpath.asPath)
```

Closing this issue.
