### ISSUE TITLE
duplicate webApplication configuration for loose application

### ISSUE THREAD

**Issue by patricktiu** [WASdev/ci.gradle#141]
Steps to reproduce the problem

1. `git clone https://github.com/WASdev/sample.servlet.git`
2. update war and liberty configuration in the build.gradle file 
```
//war {
//    archiveName = baseName + '.' + extension
//}

liberty {
    server {
        bootstrapProperties = ['default.http.port': testServerHttpPort,
                               'default.https.port': testServerHttpsPort,
                               'appLocation': "${rootProject.name}-${version}.war",
                               'appContext': warContext]
        name = wlpServerName
        apps = [war]
        stripVersion = false
    }
}
```
3. build the project and check `build/wlp/usr/servers/LibertyProjectServer/configDropins/configDropins/defaults` directory.

I guess the issue is caused by setting `stripVersion=false`

**Comment by patricktiu** [comment]
Should the `id` attribute in the `<webApplication/>` element in install_apps_configuration_741776.xml set to $rootProject.name?

**Comment by jjvilleg** [comment]
The id attribute is set by whatever war.basename ends up being. The war plugin usually defaults to rootProject.name if it isn't set in the build.gradle file.
