### ISSUE TITLE
Question: How do I enable server debug mode via gradle?

### ISSUE THREAD

**Issue by leucir** [WASdev/ci.gradle#149]
I need to debug my server locally before pushing the code to production. I couldn't find in the documentation anything related to that.

**Comment by cthigh** [comment]
To debug your application running on the server, you can start the server using the `libertyDebug` task and attach a debugger using port 7777 by default.
![screen shot 2017-11-09 at 4 31 56 pm](https://user-images.githubusercontent.com/17861985/32633148-fe4a98d6-c56b-11e7-9fb1-3aa36919535f.png)

Using Eclipse, I open Debug Configurations for Remote Java Application:
![screen shot 2017-11-09 at 4 34 14 pm](https://user-images.githubusercontent.com/17861985/32633182-220e3e3a-c56c-11e7-98e0-e033acff0404.png)

Set the breakpoints needed as usual.
![screen shot 2017-11-09 at 4 32 30 pm](https://user-images.githubusercontent.com/17861985/32633245-62d3dde4-c56c-11e7-8df5-95ce78a6d8f6.png)

**Comment by cthigh** [comment]
Reopen if you have additional questions in this area.
