### ISSUE TITLE
whenFileExists returns 22

### ISSUE THREAD

**Issue by aqubit** [WASdev/ci.gradle#15]
Hi there!

The issue is as follows. When you pass 'whenFileExists=ignore' to the installFeature task, and the feature exists, IBM's featureManager returns 22 even though you are telling it to ignore it . Gradle will consider this 22 code as a failure. I wonder if the plugin, provided the ignore flag was passed, could translate the 22 to 0. 

Kind regards,

Cesar

http://www-01.ibm.com/support/knowledgecenter/was_beta_liberty/com.ibm.websphere.wlp.nd.multiplatform.doc/ae/rwlp_command_featuremanager.html

**Comment by oscarlv** [comment]
Thanks for your feedback, Cesar. We're gonna considerate your sugestion. Just for curiosity, are you trying to reinstall a feature?

**Comment by jgawor** [comment]
The underlying Ant task code has been updated to accept exit code 22 so this should be resolved now. See https://github.com/WASdev/ci.ant/issues/27.
