### ISSUE TITLE
Cannot run installLiberty?

### ISSUE THREAD

**Issue by hrstoyanov** [WASdev/ci.gradle#158]
Here is a snippet of my build file:
```
liberty {
    server {
        name = 'myServer'
        dropins = [war]
        stripVersion = true
    }
    
    install {
        version = '17.0.0_03'
        type = "microProfile1"
    }
    
}
```

![image](https://user-images.githubusercontent.com/5327044/32871043-a97bd712-ca33-11e7-8ca5-20b2a3d10ff3.png)

**Comment by hughesj** [comment]
Hi, have you tried using version = '17.0.0.3'

**Comment by hrstoyanov** [comment]
Nope:
```
Execution failed for task ':installLiberty'.
> java.lang.IllegalArgumentException: Invalid version: 17.0.0.3
```

**Comment by hrstoyanov** [comment]
I ma coming to the conclusion that this gradle plug-in has not been testing with OpenLibery MicroProfile - several of the gradle task fail in way that shows exactly that.

**Comment by hrstoyanov** [comment]
Will close this for now - it seems as Cindy gave me more info [here](https://stackoverflow.com/questions/47018807/open-liberty-features)
