### ISSUE TITLE
The libertyCreate task is not copying the modified src server.xml to the server directory

### ISSUE THREAD

**Issue by eharris369** [WASdev/ci.gradle#161]
If I modify the src server.xml and then run 'gradle libertyCreate', the changes do not get copied to the server directory in the build folder.

**Comment by eharris369** [comment]
Cindy pointed out the following: You can use the `--rerun-tasks` option to force it and that works. Gradle thinks the task should not run when it should.

**Comment by hrstoyanov** [comment]
Confimed issue with Gradle 4.3.1 on MacOS. Can we get an updated plugin asap, please?

**Comment by keithchong** [comment]
@eharris369, @cthigh , I have a config file that includes another file.   The included file is not being copied over.  Is this a known problem?

**Comment by mattbsox** [comment]
@keithchong If you are just specifying a config file then the included file will not be copied. You can use the configDirectory property to copy the folder that contains both of these files into the server directory.

**Comment by keithchong** [comment]
Thanks @mattbsox .  That's what was missing.  It works, and it also copies the subfolders too.
