### ISSUE TITLE
Shouldn't need Liberty to download the plugin

### ISSUE THREAD

**Issue by katheris** [WASdev/ci.gradle#17]
One of the dependencies for the plugin is a ws-server.jar which you can only get by downloading a copy of Liberty. This is different from the Liberty-Maven plugin and makes the installLiberty task useless since you need a copy of Liberty to get the plugin to let you run the installLiberty. You should be able to download the plugin without having a copy of Liberty and then download Liberty using the installLiberty task.

**Comment by oscarlv** [comment]
Hi, do you have the last snapshot version or did you compile your own version?

**Comment by katheris** [comment]
I compiled my own version, the installLiberty task doesn't appear to be on the latest snapshot on Maven Central.

**Comment by MParrao** [comment]
Does this issue have the same scenario of #13 or does it have anything different?

**Comment by katheris** [comment]
It seems to be the same scenario, although I only built a version recently, weirdly I pulled down the code again and rebuilt today and now it works, so I don't know why I didn't have the fix before. Can the readme be updated to remove this dependency? Do you know when this update will go into the copy on Maven Central or https://oss.sonatype.org/content/repositories/snapshots? Thanks for your help.

**Comment by Justoce** [comment]
This issue is already done.. It is solve with the new ant version. It is necessary something else?

**Comment by katheris** [comment]
The readme file still states that you have to include a ws-server.jar as a dependency, this doc should be updated because it indicates that you do have to have Liberty installed to use the plugin, which is not true.

**Comment by jgawor** [comment]
Closing as the documentation is now updated.
