### ISSUE TITLE
The file {0} being validated does not exist.

### ISSUE THREAD

**Issue by baumato** [WASdev/ci.gradle#18]
Hi,
thanks for this plugin.

I hope to get help with following issue:

    [ant:deploy] CWWKM2013I: Die validierte Datei C:\Apps\FIDE\wlp\usr\servers\defaultServer\logs\console.log ist nicht vorhanden.

It translates to:

    CWWKM2013I: The file {0} being validated does not exist.

My gradle.build:

```
apply plugin: 'java'
apply plugin: 'war'
apply plugin: 'liberty'

repositories {
    jcenter()
}

buildscript {
    dependencies {
        classpath files('C:\\Apps\\FIDE\\gradle-2.5\\wlp-plugin\\wlp-anttasks.jar')
        classpath files('C:\\Apps\\FIDE\\gradle-2.5\\wlp-plugin\\liberty-gradle-plugin.jar')
        classpath files('C:\\Apps\\FIDE\\wlp\\bin\\tools\\ws-server.jar')
    }
}

liberty {
    wlpDir = 'C:\\Apps\\FIDE\\wlp'
    serverName = 'defaultServer'
    deploy {
    	file = 'C:/Data/git/Experiments/Experiment/build/libs/Experiment.war'
    }
    packageLiberty{
        archive = "MyServerPackage.zip"
        include = "usr"
    }
    dumpLiberty{
        archive = "C:/Temp/Dump.zip"
        include = "heap, system"
    }
    javaDumpLiberty{
        archive = "JavaDump.zip"
        include = "system"
    }
}
```

Best regards.

**Comment by oscarlv** [comment]
Hi, did you start the server before make the deploy?

**Comment by baumato** [comment]
Hi,
thank you for the answer.

I tried both. Starting the server and then call gradle deploy and call gradle deploy without starting the server. In both cases I get the error message and then a timeout at the end.
However, it seems when I start the server first then the deployment works but I have to wait for the timeout.

Best regards.

**Comment by baumato** [comment]
I cannot find the console.log file in folder: 

    C:\Apps\FIDE\wlp\usr\servers\defaultServer\logs

There is only a messages.log file.

The logging configuratin in my wlp server.xml is as follows:

    <logging consoleLogLevel="INFO" copySystemStreams="true"/>

**Comment by baumato** [comment]
There seems to be a difference between starting the server using the terminal with

    server start

command and starting the server using eclipse (with the WebSphere Application Server Liberty Profile Development Tools installed). In the latter the console.log file gets not created. It's a pity.

Deploying works when starting the wlp in the terminal.

**Comment by baumato** [comment]
Last message on this issue :-)
As a workaround for eclipse, the server can be configured like this:

    <logging consoleLogLevel="INFO" copySystemStreams="true" messageFileName="console.log"/>
Then deploying in terminal with

    gradle deploy
works.
