### ISSUE TITLE
This plugin is trying to execute a missing executable?

### ISSUE THREAD

**Issue by hrstoyanov** [WASdev/ci.gradle#184]
I am using 2.0.2-SNAPSHOT and I am getting:
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':recres-webapp:installFeature'.
> java.io.IOException: Cannot run program ""C:\temp\my-webapp\build\wlp\bin\installUtility.bat"" (in directory "C:\temp\mys-webapp\build\wlp"): CreateProcess error=2, The system cannot find th
e file specified
```

When I look into my OpenLiberty  17.0.0.3 server folder, previously installed by th same plugin ```installLiberty```, indeed __installUtility.bat__ is not there. **What is going on? **

Workaround until this gets fixed -start the server manually:
```\build\wlp\bin\server.bat --debug```

**Comment by hrstoyanov** [comment]
I noticed that I need to do something like:
```
<featureManager>
        <feature>microProfile-1.2</feature>
        <feature>webProfile-7.0</feature>
</featureManager>
```
to get enough scripts in wlp/bin for this plug-in to be working. OpenLibeerty Microprofile comes with no *.bat utilities, so this plug-in should not rely on this.

**Comment by mattbsox** [comment]
We do not support installUtility when using an OpenLiberty runtime. We acknowledge this [here](https://github.com/WASdev/ci.gradle/blob/master/docs/installFeature.md).

**Comment by hrstoyanov** [comment]
Okm

**Comment by hrstoyanov** [comment]
Maybe I am missing something obvious here, but how do you intened to start open liberty server if ``` gradlew libertyStart``` does not work?

**Comment by mattbsox** [comment]
You should be able to call `libertyStart` without any issues as long as you don't have a `features` block configured in your build.gradle. You'll need to configure them with the featureManager in your server.xml like you did above.

**Comment by hrstoyanov** [comment]
Thanks @mattbsox . I had a spurious dependency on ```installFeature``` that was causing all this. Once it was removed, the ```libertyStart``` became operational. Closing this issue now.
