### ISSUE TITLE
Build a 2.2-SNAPSHOT since 2.1 was released.

### ISSUE THREAD

**Issue by cthigh** [WASdev/ci.gradle#191]
Also, update the README.md to indicate the latest snapshot is 2.2-SNAPSHOT.

**Comment by cherylking** [comment]
Update the readme so that the snapshot release is not hardcoded. Our latest release is 2.4.1.

**Comment by cherylking** [comment]
We are not going to update the referenced snapshot in the readme each release. It should be obvious to put the snapshot release that you want in your build.gradle.
