### ISSUE TITLE
liberty-plugin-config.xml not created if using installDir

### ISSUE THREAD

**Issue by keithchong** [WASdev/ci.gradle#197]
I wanted to use a pre-installed version of Liberty by using the attribute "installDir".  See:

https://github.com/WASdev/ci.gradle/blob/master/docs/libertyExtensions.md#liberty-extension-properties

I modified one of the samples, built it successfully, and was able to do a libertyStart and libertyStop, and checked my java process to ensure the correct server is started and stopped.

However, the plugin file was not created in the build folder.

**Comment by aguibert** [comment]
This has been fixed by the following PR (not in a released version yet):
https://github.com/WASdev/ci.gradle/pull/195

Also this issue is a dup of:
https://github.com/WASdev/ci.gradle/issues/194
