### ISSUE TITLE
Install feature task

### ISSUE THREAD

**Issue by jgawor** [WASdev/ci.gradle#2]
Add a task for installing features based on https://github.com/WASdev/ci.ant/blob/master/src/main/java/net/wasdev/wlp/ant/InstallFeatureTask.java.

**Comment by TanyRay** [comment]
Add output to IDE console in  deployWar task.

**Comment by oscarlv** [comment]
This is ready for a review on #4 .

**Comment by oscarlv** [comment]
This was already merged in 19431976, is anything else needed?, I think this could be closed.

**Comment by rmcmx** [comment]
Looks like this can be closed. Please reopen if more work is needed.
