### ISSUE TITLE
Project properties not seen in server.xml processing?

### ISSUE THREAD

**Issue by hrstoyanov** [WASdev/ci.gradle#201]
Why is this _not_ possible:
If you define a property in the Gradle project, for example:
```
build.properties
-----------------
odbjca_version=1.0.0-SNAPSHOT
```
and then reference the property inside the ```server.xml``` source, like:
```
src/main/liberty/config/severs.xml
----------------------------------
<resourceAdapter
location="${server.config.dir}/jca/odbjca/odbjca-rar-${odbjca_version}.rar">
</resourceAdapter>
```

One would expect that as this plug-in processes the input server.xml, it would substitute Gradle project properties, if referenced...

How could I achieve the same effect if there is an alternative here?

**Comment by cthigh** [comment]
You can use bootstrap.properties for that purpose.  You can either inline your bootstrap properties in your liberty configuration or add a separate file with your server.xml.

https://github.com/WASdev/ci.gradle/blob/master/docs/libertyCreate.md#libertycreate-task
bootstrap.properties will be substituted into server.xml by the runtime.

**Comment by hrstoyanov** [comment]
Thanks!
