### ISSUE TITLE
Web facet set to 3.0 but EAR facet set to 5.0

### ISSUE THREAD

**Issue by eharris369** [WASdev/ci.gradle#210]
If I import a project that has ear and war sub-projects, for the ear project the EAR facet is set to 5.0 (which is JEE5) and for the war project the Dynamic Web Module facet is set to 3.0 (which is JEE6).  I can't find that it is causing any problems but could the EAR facet be set to 6.0 to be consistent with the web facet?

**Comment by cherylking** [comment]
I just verified that we are setting the EAR facet to 6.0 if it is not specified, and the war sub-projects to 3.0. Is it possible that your ear project specified the 5.0 facet, and war sub-projects did not specify a facet. Then we set the facets for the war sub-projects to 3.0?

**Comment by eharris369** [comment]
I can't see any place that I am setting it unless it is implied in some other way.  I tried again, deleted all .gradle folders in the project and in home dir.  I still see the problem.  Attaching my test case.  Unzip and then do 'gradle build' inside ee1 and then import ee1 into Eclipse 4.7.2.
[ee1.zip](https://github.com/WASdev/ci.gradle/files/1704543/ee1.zip)
