### ISSUE TITLE
Web facet set to 2.4 instead of 3.0 for simple web project

### ISSUE THREAD

**Issue by eharris369** [WASdev/ci.gradle#211]
I have a simple web project and I do a 'gradle build' on it and then import it into eclipse as an existing Gradle project.  If I use the 2.1.1-SNAPSHOT the Dynamic Web Module facet is set to 2.4 instead of 3.0.  If I use the 2.1 release then the Dynamic Web Module facet is set to 3.0 as expected.

**Comment by cherylking** [comment]
Fixed by #212
