### ISSUE TITLE
default features list not installing server.xml features

### ISSUE THREAD

**Issue by ryanesch** [WASdev/ci.gradle#214]
Following the examples on https://github.com/WASdev/ci.gradle/blob/master/docs/installFeature.md#installfeature-task, I was able to get openidconnectclient-1.0 installed using:
```
liberty {
	server {
		features {
			name = ['openidconnectclient-1.0']
       		        acceptLicense = true
		}
	}
}
```
However, if I don't explicitly name openidconnectclient-1.0, it will not install even though it is listed in my server.xml feature list. If I understand correctly, all features listed in my server.xml should be installed if I include:
```
liberty {
	server {
		features {
       		        acceptLicense = true
		}
	}
}
```

**Comment by jjvilleg** [comment]
Just made a PR to resolve this issue. A bit of our logic in the liberty.groovy file needed to be refined. After it's merged , we will push out a snapshot to make sure this fixes your problem.

**Comment by jjvilleg** [comment]
The PR has been merged and we have just updated our snapshot. Try testing this on our 2.1.1-SNAPSHOT and let us know if this resolves your issue.

**Comment by jjvilleg** [comment]
I'm closing this issue since it should be resolved. If this is still a problem, please reopen the issue.
