### ISSUE TITLE
Application removed after second gradle assemble installApps

### ISSUE THREAD

**Issue by eharris369** [WASdev/ci.gradle#226]
Using the attached sample, unzip and then from within the jee7sample folder run:
    _gradle assemble installApps -x test -x libertyPackage_
Check that in jee7sample-ear/build/wlp/usr/servers/jee7sampleServer/configDropins/defaults there is a file called install_apps_configuration_741776.xml.  This file has the application element in it to deploy the application.
Now run the same command again:
    _gradle assemble installApps -x test -x libertyPackage_
The install_apps_configuration_741776.xml file is now gone and the app is no longer deployed.

Using: net.wasdev.wlp.gradle.plugins:liberty-gradle-plugin:2.1.1-SNAPSHOT

[jee7sample.zip](https://github.com/WASdev/ci.gradle/files/1782677/jee7sample.zip)

**Comment by ericdylanpeters** [comment]
@eharris369 - is this a regression ?
