### ISSUE TITLE
running Liberty in a bound command

### ISSUE THREAD

**Issue by scphantm** [WASdev/ci.gradle#237]
We are having huge problems with liberty here, i'm very close to just scrapping this thing and writing my own gradle plugin from scratch.  The core of the current problem is simple, this plugin executes liberty in forked processes and relinquishes control of those processes.  If you look at every other server plugin i have seen, jboss, nodejs, spring boot, etc, they are all bound executables.  meaning gradle doesn't just execute the start task, dump to null and move on, it executes the server start command and waits for the process to end.  either manually (ctrl-c) or via a second gradle command (./gradlew bootStop in spring boot's case).  This is done so that if the build ends, the spawned process ends.  Those other developers do this to prevent exactly the problem i am wrestling with.  The fact that you can quite easily trick gradle into deleting the server folders while liberty is running, leaving the spawned process running, therefore leaving orphaned processes.  My record so far is 37 copies before i realized what was going on.

Before i dive into the bowels of that Ant plugin and rewrite that trying to fix this, my question is, why exactly did you design this to operate that way to being with?  Was there a tech issue?  design issue that isn't apparent to me?  you didn't know any better?  what was the reason?

Is there something that you have built in that prevents this already?  maybe something i mistakenly stripped out in the 3.x branch?

**Comment by dshimo** [comment]
Hi @scphantm, thank you for your insights. 
The decision for the Liberty Gradle plugin to use common Ant tasks was made before the current devs; probably an effort to quickly bring it on par with the Liberty Maven plugin. The focus on adding functionality slowly cemented this design choice. This parallelism with Maven likely tunnel-visioned us, making us fail to recognize Gradle’s uniqueness and its special set of features. With that, we acknowledge that the code could use a major refactor and appreciate your input for version 3.X. IBM is making the effort to go open source exactly for these kinds of developer interactions.

What are your recommended steps we should take to directly improve our plugin?

* What are the other server plugins doing right that you’d like to see our in our Liberty plugin? Do we have our Gradle approach wrong? Do you have an example of an ideal Gradle plugin? Is using Ant already a misstep in your opinion?
* We’re continuing to learn how Gradle handles daemons and processes and `libertyRun` is a highlight of such struggles. We could use `libertyStop` from a second command line as you mentioned, but we know many prefer the ability to Ctrl-C a run script and want to improve ours. From what I’ve researched, Gradle has admitted to a design conflict with handling Ctrl-C’s/SIGINT signals to cancel the build versus killing the foreground process. shutDownHooks seem to provide an undesirable delayed effect. Is our looseness in orphaning processes tied to Gradle or our Ant implementation? Somewhere in between? Is there a working solution we should be looking at?

We appreciate your feedback and look forward to hearing back from you.

**Comment by scphantm** [comment]
Unfortunately, we decided earlier this week to abandon this approach and write our own plugin based off the spring boot gradle code base.  Me and the people that decided that have many issues with this plugin.

1) the issue above.  The only real fix for this we can see is eliminate the Ant plugin all together, and have Gradle take over everything with controlling processes.  This is is a big effort, on top of the hundreds of hours i have put into this trying to pull things apart and rebuild them in a gradle enterprise friendly world.  Its no longer worth the effort.  Especially for something we can't open a PMR for if there are problems in the future.

2)  There's too much to this thing.  Its too flexible.  This is the part that has taken me 6 months to try to unwind and rebuild with this thing.  There are too many ways to accomplish the same thing.  We are talking developer workstations here.  By the time I got our configuration deployment system in (because 100% of our projects are multi-module projects, unlike everything here) we counted 9 different ways to configure deploying a single application.  And then, since we run multi-module projects, you can have any number of any combination of that 9.  I have to roll this out to 1000 developers on 600 different applications, and support it.  our department will get crushed with support tickets with developers trying to configure their desktops one way, that blows up on the server because the servers are configured another way.

This isn't a complaint leveled against you all specifically, it has plagued IBM products for decades.  This plugin simply follows the model.  IBM products are very predictable.  Big, bloated, 5 times the features it should have, missing half the features it really needs, none of them work particularly well, and they will be glad to explain it to you for $260 an hour 160 hour minimum.  And, as an added bonus, when you act as IBM's testing department for more than 1 year, you get 5 free tickets to interconnect.  (but travel and lodging are on you of course)

Sound familiar?

3)  Liberty documentation in general is bad.  Just for fun, i searched "deploy app to liberty" on google and randomly selected 5 articles.  it was funny because all 5 articles had different procedures to deploying an app to liberty.  and 2 of them were flat out wrong, we already proved it doesn't work like that.  Now to make this even better, i specifically selected articles on IBM sites.  Doing things my way, they don't have to think about liberty.  they just apply the plugin and do '/gradlew libertyRun' and everything just works.  no configuring no nothing.  That way we can simply publish docs on how to use OUR version of liberty, and if we get support tickets for people trying to do something creative, we can simply tell them, ignore the IBM docs and do it our way, gradle will guide you.  Then gradle will never expose a function or capability that we don't support on our production clusters.

Thats the thinking that went into the decision.  Once i get out of this time crunch i will approach my VP on releasing our plugin as an OSS project.  He wants to increase our OSS footprint, this would be a good one to do it with.

Thanks all

**Comment by dshimo** [comment]
Thank you @scphantm for speaking to us about this issue; this has provided us a better perspective of our plugin and its users. We'll be taking these thoughts along with us as we continue development. 
I personally wish you luck on your endeavors and am interested to see your plugin when it's released.

**Comment by cherylking** [comment]
Opened issue #238 to address the main point of this issue. We'll take your other thoughts and observations into consideration and open other issues as seems appropriate. Thanks.
