### ISSUE TITLE
The liberty-plugin-config.xml gets updated on second call to gradle assemble installApps

### ISSUE THREAD

**Issue by eharris369** [WASdev/ci.gradle#244]
The liberty-plugin-config.xml file gets updated on a second call to gradle assemble installApps even though nothing has changed.  This fails with 2.2 and with 2.3-SNAPSHOT.  The problem can be reproduced with the attached sample.  Unzip and then from inside the sample do the following:

1. gradle assemble installApps
2. check the size of liberty-plugin-config.xml in the build directory
3. gradle assemble installApps
4. check the size of liberty-plugin-config.xml again - it is bigger now

[ServletSample.zip](https://github.com/WASdev/ci.gradle/files/1876905/ServletSample.zip)

**Comment by jjvilleg** [comment]
I extrapolated some installApps configuration to the AbstractServer Task in order to add the missing property at create instead of running for installApps to run. Hopefully this resolves your issue. 

#248

**Comment by jjvilleg** [comment]
Closing this issue because #251 resolves it.
