### ISSUE TITLE
installApps doesn't create the apps (or dropins) output folder

### ISSUE THREAD

**Issue by efussi** [WASdev/ci.gradle#246]
If you use the _installApps_ task to install a war file to a server that was created from a server template which doesn't contain empty _apps_ and _dropins_ folders (like the defaultServer template does), then it fails with an exception like the following:

```
Execution failed for task ':MyApp:installApps'.
> java.nio.file.NoSuchFileException: C:\dev\MyApp\build\libs\MyApp.war -> C:\dev\MyApp\build\wlp\usr\servers\MyServer\apps\MyApp.war
```

IMO, the _installApps_ task should create its output folder if necessary instead of relying on it being there in the server (template). I am using version 2.2 of the Liberty Gradle plugin.

**Comment by mattbsox** [comment]
Is the template provided by Liberty or is it a custom template?

**Comment by cthigh** [comment]
This request makes sense. Our typical server creation creates both the apps and dropins folders by default.  In this scenario, the plugin can just create the folder that is needed if it does not already exist.
