### ISSUE TITLE
consider publishing a Changelog

### ISSUE THREAD

**Issue by corporate-gadfly** [WASdev/ci.gradle#252]
Would you consider publishing a changelong?

I have an arquillian configuration and several integration tests that work very nicely for version 2.2 of the plugin. After bumping to 2.3, none of my integration tests work. Before I delve into the root cause of the failures, it would be helpful if there was a changelog.

**Comment by chyt** [comment]
We publish release notes with every release. The 2.3 release notes are [here](https://github.com/WASdev/ci.gradle/releases/tag/liberty-gradle-plugin-2.3). 

We didn't change anything with `configureArquillian` in the 2.3 release aside from supporting it with multiple servers in the same build file. However, the old configuration method introduced in 2.2 should still work.

Can you post steps on how to recreate the issue, or share your project with us?

**Comment by corporate-gadfly** [comment]
Thanks for the reply and the link.

It would be pretty hard for me to share a project without releasing proprietary work. However, I was able to get 2.3 running by changing my `serverName` to `defaultServer`. With 2.2, I was able to use another name, e.g., `specialBatchServer`, etc.

I'm okay with closing this one.
