### ISSUE TITLE
Add "os" parameter to the package sever in gradle

### ISSUE THREAD

**Issue by Justoce** [WASdev/ci.gradle#26]
It would be nice to have the "os" parameter in gradle, it can help to reduce the package size result.

More information: http://www-01.ibm.com/support/knowledgecenter/SSEQTP_8.5.5/com.ibm.websphere.wlp.doc/ae/twlp_setup_package_server.html?cp=SSEQTP_8.5.5%2F1-3-11-0-3-2-1-6

**Comment by Justoce** [comment]
You can solve it with this: https://github.com/WASdev/ci.gradle/pull/27

**Comment by jgawor** [comment]
Merged. Thanks!
