### ISSUE TITLE
Multiple server clojures

### ISSUE THREAD

**Issue by ryanesch** [WASdev/ci.gradle#274]
Is something like the following possible?
```
liberty {
    install {
        baseDir = rootProject.buildDir
    }
    server {
		name = 'Servlet1'
                ...
   }
    server {
		name = 'Servlet2'
                ...
   }
}
```
Seems like they are combined into one or one of them is ignored.

**Comment by mattbsox** [comment]
Yes, the servers should share the same server runtime but have their own server directories inside the installDir. You'll need to have a `servers` closure like this:
```
liberty {
    install {
        baseDir = rootProject.buildDir
    }
    servers {
        servlet1 {
            ...
        }
        servlet2 {
            ...
        }
    }
}
```

**Comment by cherylking** [comment]
@ryanesch Can this be closed? Did Matt's response suffice?

**Comment by ryanesch** [comment]
Yes
