### ISSUE TITLE
Missing SNAPSHOT artifacts

### ISSUE THREAD

**Issue by bsfarrell** [WASdev/ci.gradle#28]
I started seeing this error over the weekend.  Seems like there was a 1.1 release of other projects, but not this one.  Does the project need a 1.1 release as well?

<pre>   > Could not resolve net.wasdev.wlp.ant:wlp-anttasks:1.1-SNAPSHOT.
     Required by:
         com.ibm.watson.wea.concierge:concierge-test:0.0.1-SNAPSHOT > net.wasdev.wlp.gradle.plugins:liberty-gradle-plugin:1.0-SNAPSHOT
      > Could not resolve net.wasdev.wlp.ant:wlp-anttasks:1.1-SNAPSHOT.
         > Could not parse POM https://oss.sonatype.org/content/repositories/snapshots/net/wasdev/wlp/ant/wlp-anttasks/1.1-SNAPSHOT/wlp-anttasks-1.1-20151107.030858-30.pom
            > Could not find net.wasdev.maven.parent:java7-parent:1.4-SNAPSHOT.
</pre>

Thanks!

**Comment by jgawor** [comment]
Sorry about that. I published a new snapshot of the project that should resolve this. We are in the middle of releasing the [ci.ant](https://github.com/WASdev/ci.ant) and [ci.maven](https://github.com/WASdev/ci.maven) projects and some of the snapshots might have gotten out of sync.

**Comment by bsfarrell** [comment]
Thanks for the quick response.
