### ISSUE TITLE
Issue importing the plugin correctly

### ISSUE THREAD

**Issue by anselmringleben** [WASdev/ci.gradle#3]
Hi,
I'm trying to import the plugin as is stated in the readme.md file.

To simplify matters I created an empty project and copied the JAR file into it. The build.gradle file looks like this (although I already tried several versions):
`buildscript {
	dependencies {
        classpath files('liberty-gradle-plugin-1.0-SNAPSHOT.jar')
        classpath files('c:/devend/wlp/bin/tools/ws-server.jar')
    }
}

apply plugin: 'liberty'

liberty {
	wlpDir = 'c:/devenv/wlp'
	serverName = 'test'
}`

I'm always getting this error message:
c:\devenv\projects\test>gradle libertyRun

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\devenv\projects\test\build.gradle' line: 6

* What went wrong:
A problem occurred evaluating root project 'test'.
> Failed to apply plugin [id 'liberty']
   > Plugin with id 'liberty' not found.

Can you help me with this please?

**Comment by davidcurrie** [comment]
Hi @anselmringleben - that's the error I'd expect to see if it isn't loading the plugin JAR. Are you sure that the path 'liberty-gradle-plugin-1.0-SNAPSHOT.jar' is correct?

**Comment by anselmringleben** [comment]
Hi @davidcurrie Thanks for replying this fast! In my test project the setup is as simple as possible: build.gradle and the JAR file are both directly in the project directory. So I guess it is correct.

**Comment by anselmringleben** [comment]
Debug output: https://www.dropbox.com/s/gxkzux1ljoxx23y/--debug.txt?dl=0
Stacktrace output: https://www.dropbox.com/s/0yjoliw6o992t81/--stacktrace.txt?dl=0

**Comment by anselmringleben** [comment]
especially in stacktrace output it seems that the plugin initialization fails.

**Comment by jgawor** [comment]
Typo (devend vs devenv) in:

classpath files('c:/devend/wlp/bin/tools/ws-server.jar')
vs.
wlpDir = 'c:/devenv/wlp'

**Comment by jgawor** [comment]
I did also discover a couple of issues (in doc & code). I updated the code and published a new snapshot of the plugin.
