### ISSUE TITLE
Loose application with persistence.xml and JPA 2.2 requires <class> elements.

### ISSUE THREAD

**Issue by dannemano** [WASdev/ci.gradle#301]
Hi all,

When I package a normal WAR with Gradle (`gradle war`) I can deploy it to Open Liberty's dropin folder without issues.
I use JPA 2.2. and a persistence.xml under /resources/META-INF/persistence.xml

When I generate a loose application XML for the same application, I get the following warning during startup:
```
[WARNING ] CWWJP9991W: The collection of metamodel types is empty. Model classes may not have been found during entity search for Java SE and some Java EE container managed persistence units.  Please verify that your entity classes are referenced in persistence.xml using either <class> elements or a global <exclude-unlisted-classes>false</exclude-unlisted-classes> element
```
My gradle config looks like this:
```
liberty {
    installDir="/Users/daniel/standalone/wlp"
    server {
        looseApplication=true
        stripVersion=true
        name="appname"
        dropins = [war]
    }
}
```

Of course the rest of the application fails as it depends on the JPA entities.
Adding an explicit `<class>` element solves the issue, but should not be necessary.

This is my persistence.xml:
```
<?xml version="1.0" encoding="UTF-8"?>
<persistence version="2.2"
             xmlns="http://xmlns.jcp.org/xml/ns/persistence" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
             xsi:schemaLocation="http://xmlns.jcp.org/xml/ns/persistence http://xmlns.jcp.org/xml/ns/persistence/persistence_2_2.xsd">
    <persistence-unit name="db2-persistence-unit" transaction-type="JTA">
        <jta-data-source>jdbc/db2</jta-data-source>
        <!-- xdahe: Listing classes not needed  when packaging a WAR. This looks like a bug in ci.gradle liberty plugin-->
        <class>my.Entity</class>

    </persistence-unit>
</persistence>
```

Part of the XML for the loose application looks like this, I cant see anything wrong with it:
```
 <dir sourceOnDisk="/<snip>/src/main/webapp" targetInArchive="/"/>
    <dir sourceOnDisk="/<snip>/build/classes/java/main" targetInArchive="/WEB-INF/classes/"/>
    <dir sourceOnDisk="/<snip>build/resources/main" targetInArchive="/WEB-INF/classes/"/>
... and some more dependencies to thirdparty libs.
```

**Comment by mattbsox** [comment]
Can you try adding `<exclude-unlisted-classes>false</exclude-unlisted-classes>` to your `persistence-unit` element in place of defining the class?

**Comment by dannemano** [comment]
Yes I tried that element as well. The error is still the same.

**Comment by dannemano** [comment]
Can the issue be related to that Gradle keeps classes and resources separated until war-packaging?

When I have built and generated a loose application, the folder /build/classes/java contains only classes. The META-INF folder us under /build/resources/main/

Can it be that EclipseLink scans for entities relative to this folder and therefore does not automatically find any annotated classes?

Of course this issue does not happen when the war is properly packaged and deployed.

**Comment by mattbsox** [comment]
Ya, that seems like it could be the issue, or at least a part of it. [This post](https://discuss.gradle.org/t/jpa-entity-classes-are-not-discovered-automatically-with-gradle/11339/6) seems to back that up as well.

One of the suggestions they give is setting the resourcesDir in build to the same directory as the generated classes, so:
```
sourceSets.main.output.resourcesDir = sourceSets.main.output.classesDir
```
That ensures everything is in the same folder so the class files won't be nonexistent/missing. Might give that a try.

**Comment by dannemano** [comment]
Updating the build.gradle with:

`sourceSets.main.output.resourcesDir = sourceSets.main.java.outputDir`

fixed it. (the old format was deprecated). I verified that both loose applications and normal packaging as war works with no class-entries in persistence.xml.

Thanks.

Not sure if it is a good idea that the liberty gradle plugin should make this modification automatically. Anyway it would be good to have documented under the installApps task.

**Comment by mattbsox** [comment]
Sure, will do. Thanks!
