### ISSUE TITLE
Add support install jar to shared library from jcenter or mavenCentral repositories

### ISSUE THREAD

**Issue by pipinet** [WASdev/ci.gradle#306]

**Comment by mattbsox** [comment]
Can you elaborate a little bit more on what you'd like to do here? If you could provide an example build.gradle file we can help you configure it to accomplish that.

**Comment by pipinet** [comment]
like https://github.com/WASdev/sample.jpa.git

**Comment by mattbsox** [comment]
You can use configurations to accomplish this as seen in the example you linked. It would be redundant to add the same behavior to the Liberty Gradle Plugin. This can already be accomplished with built-in Gradle constructs.

**Comment by pipinet** [comment]
@mattbsox ok, thanks.

**Comment by cherylking** [comment]
Closing as there is no action for us to take on this issue.
