### ISSUE TITLE
Eclipse .classpath paths and loose application paths are inconsistent

### ISSUE THREAD

**Issue by aguibert** [WASdev/ci.gradle#314]
One of the biggest devexp features of Liberty is that your IDE can compile code for you and Liberty can "hot update" the app in a few milliseconds, without needing to restart the app or server.

When make a standard java gradle project, my .classpath looks like this:
```xml
<classpath>
	<classpathentry kind="src" output="bin/main" path="src/main/java">
		<attributes>
			<attribute name="gradle_scope" value="main"/>
			<attribute name="gradle_used_by_scope" value="main,test"/>
		</attributes>
	</classpathentry>
	<classpathentry kind="src" output="bin/test" path="src/test/java">
		<attributes>
			<attribute name="gradle_scope" value="test"/>
			<attribute name="gradle_used_by_scope" value="test"/>
		</attributes>
	</classpathentry>
	<classpathentry kind="src" output="bin/test" path="src/test/resources">
		<attributes>
			<attribute name="gradle_scope" value="test"/>
			<attribute name="gradle_used_by_scope" value="test"/>
		</attributes>
	</classpathentry>
	<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-1.8/"/>
	<classpathentry kind="con" path="org.eclipse.jst.j2ee.internal.web.container"/>
	<classpathentry kind="con" path="org.eclipse.buildship.core.gradleclasspathcontainer">
		<attributes>
			<attribute name="org.eclipse.jst.component.dependency" value="/WEB-INF/lib"/>
		</attributes>
	</classpathentry>
	<classpathentry kind="output" path="bin/default"/>
</classpath>
```

And my generated loose application looks like this:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<archive>
    <dir sourceOnDisk="/Users/aguibert/dev/git/basic-liberty/src/main/webapp" targetInArchive="/"/>
    <dir sourceOnDisk="/Users/aguibert/dev/git/basic-liberty/build/classes/java/main" targetInArchive="/WEB-INF/classes/"/>
    <file sourceOnDisk="/Users/aguibert/dev/git/basic-liberty/build/tmp/META-INF/MANIFEST.MF" targetInArchive="/META-INF/MANIFEST.MF"/>
</archive>
```

So, Eclipse is compiling my application classes into `bin/main`, but my loose application is pulling application classes from `build/classes/java/main`. For hot updates to work, these two locations need to be the same.

For now, I have to work around this issue by noticing that my app updates aren't taking effect, and then go hand-edit my .classpath. But any time I re-sync my gradle project (e.g. add/update a dependency) then the .classpath gets overwritten.

**Comment by mattbsox** [comment]
Interesting, I'll take a look at this. Is your project using the `eclipse` plugin in its build file? If so, we can just pull the Eclipse classpath from there.

**Comment by aguibert** [comment]
no, my project is not using the `eclipse` plugin. I'm just using these:
```groovy
apply plugin: 'war'
apply plugin: 'liberty'
```

I pull the project into Eclipse by doing `Import -> Existing gradle project`. I think the reason this broke is perhaps an older version of Gradle wrote class files into `build/classes/java/main`, but the newer versions of Gradle may write to `bin/main`.

The repo I am referring to is publicly available here: https://github.com/aguibert/basic-liberty

**Comment by mattbsox** [comment]
@aguibert I added some classpath configuration for the Eclipse plugin inside of our plugin. It ends up setting the Eclipse output directory to `build/classes/java/main` instead of `bin/main`. From what I've read this [isn't recommended](https://discuss.gradle.org/t/eclipse-plugin-did-not-configure-default-output-directory-to-build/7586), but it works. Would configuring this in the loose app file be better or do you think changing the `.classpath` file is a valid solution?
