### ISSUE TITLE
Deploy latest version (2.6.5) to https://plugins.gradle.org/plugin/net.wasdev.wlp.gradle.plugins.Liberty

### ISSUE THREAD

**Issue by dannemano** [WASdev/ci.gradle#316]
The latest version of the plugin is not deployed to Gradle Plugins portal.
This makes it tricky to use the new Gradle Plugins DSL.

`
plugins {
     id 'net.wasdev.wlp.gradle.plugins.Liberty' version '2.6.3'
}
`

Regards,
Daniel

**Comment by cherylking** [comment]
Thanks for letting us know. We will work on releasing that early next week.

**Comment by cherylking** [comment]
@dannemano So sorry for the delay. There was an issue in our build script with the more recent versions of gradle that was preventing this release from successfully deploying. It has now been deployed.

https://plugins.gradle.org/plugin/net.wasdev.wlp.gradle.plugins.Liberty
