### ISSUE TITLE
Update installLiberty to use Maven Central

### ISSUE THREAD

**Issue by katheris** [WASdev/ci.gradle#44]
Update installLiberty to either use Maven Central by default or provide a simple mechanism for specifying that you want to install an image from Maven Central. Currently can be configured by setting the runtimeUrl to the specific location of the file on Maven Central but instead it would be better to be able to specify some configuration options, similar to ci.maven.

**Comment by cthigh** [comment]
The 2.0 release of the gradle plugin supports installLiberty maven central installation.  Specify the dependency using

```
dependencies {
    libertyRuntime group: 'com.ibm.websphere.appserver.runtime', name: 'wlp-webProfile7', version: '17.0.0.2'
}
```
https://github.com/WASdev/ci.gradle/blob/master/docs/installLiberty.md#installliberty-task
