### ISSUE TITLE
Add capability to have multiple servers defined in a single gradle file

### ISSUE THREAD

**Issue by iainduncani** [WASdev/ci.gradle#45]
I want to be able to start multiple servers from a single gradle file but can't do this as the Liberty stanza applies to the whole build project.  Something like this would be nice:

```
task startMyServer(type: LibertyStart) {
    serverName = 'myServer'
}
task startOtherServer(type: LibertyStart) {
    serverName = 'otherServer'
}
```

**Comment by cherylking** [comment]
Closing since this was delivered in release 2.3.
