### ISSUE TITLE
Question:  Does this plugin deploy using the "dropins" directory?

### ISSUE THREAD

**Issue by pford68** [WASdev/ci.gradle#49]
If so, does that conflict with configuring a `<webApplication>` in server.xml.  My understanding is that it does, or perhaps it is the other way around.  In any event, I believe they are incompatible methods of deploying a web application in Liberty, correct?

**Comment by cthigh** [comment]
I believe that deploy goes to dropins by default. If you have your application configured in server.xml, you do want it in the `apps` folder. 

Take a look at the new installApps support in version 2 of the plugin.  You can specify your war to be installed in `apps` or `dropins`. If you don't specify, it will install to `apps` and configure the application if needed in the config dropins folder.
