### ISSUE TITLE
Unable to specify bootsrap properties

### ISSUE THREAD

**Issue by iainduncani** [WASdev/ci.gradle#50]
Unlike in the Maven plugin where you can do:

```
<bootstrapProperties>
  <default.http.port>${testServerHttpPort}</default.http.port>
  <default.https.port>${testServerHttpsPort}</default.https.port>
</bootstrapProperties>
```

You can't specify bootstrap properties with the gradle plugin

**Comment by cthigh** [comment]
The 2.0 version of the plugin supports all sorts of ways to copy configuration similar to the maven plugin.  The new server properties are documented here: https://github.com/WASdev/ci.gradle/blob/master/docs/libertyExtensions.md#liberty-server-configuration

Also see examples in https://github.com/WASdev/ci.gradle/blob/master/docs/libertyCreate.md#libertycreate-task on how libertyCreate uses these properties.
