### ISSUE TITLE
Unable to specify config file

### ISSUE THREAD

**Issue by iainduncani** [WASdev/ci.gradle#51]
Unlike in the maven plugin where there is a `<configFile>src/main/liberty/config/server.xml</configFile>` element that you can add to the config to use when creating a server this isn't an option with the gradle plugin

**Comment by cthigh** [comment]
The 2.0 version of the plugin supports all sorts of ways to copy configuration similar to the maven plugin. The new server properties are documented here: https://github.com/WASdev/ci.gradle/blob/master/docs/libertyExtensions.md#liberty-server-configuration

Also see examples in https://github.com/WASdev/ci.gradle/blob/master/docs/libertyCreate.md#libertycreate-task on how libertyCreate uses these properties.
