### ISSUE TITLE
Calling the libertyStart task should invoke installLiberty

### ISSUE THREAD

**Issue by katheris** [WASdev/ci.gradle#53]
Calling the libertyStart task should invoke installLiberty, otherwise you have to add libertyStart.dependsOn('installLiberty') to the build.gradle file.

**Comment by cthigh** [comment]
The 2.0 version of the plugin improves liberty task automated dependencies.

libertyStart will now automatically call
      installLiberty
      libertyCreate
      installFeature (if configured)
      installApps (if configured)

**Comment by cthigh** [comment]
@dshimo, I thought you or I had added some more information on the new task dependency changes but I don't see it.  Can you create some documentation in this area?

**Comment by cthigh** [comment]
The dependsOn settings have been documented.
