### ISSUE TITLE
Calling the installFeature task should invoke installLiberty by default

### ISSUE THREAD

**Issue by katheris** [WASdev/ci.gradle#54]
Calling the installFeature task should invoke the installLiberty task, otherwise you have to add installFeature.dependsOn('installLiberty') to the build.gradle file.

**Comment by cthigh** [comment]
Fixed by #68.

**Comment by cthigh** [comment]
The snapshot has `installFeature` depending on `installLiberty`, but for the general case we need to change this to `libertyCreate`.  A user might want to install the features based on the server.xml configuration. For this case, we need the server created first.

**Comment by cthigh** [comment]
The 2.0 version of the plugin improves liberty task automated dependencies.

libertyStart will now automatically call
installLiberty
libertyCreate
installFeature (if configured)
installApps (if configured)
