### ISSUE TITLE
installFeature problems with 16.0.0_04

### ISSUE THREAD

**Issue by ernani** [WASdev/ci.gradle#55]
I have the latest 1.1 SNAPSHOT jars for ci.gradle and can't build my tasks due to a failure with installFeature.

I am using the following settings:

```
liberty {
	installDir = "${libertyBaseDir}/wlp"
	serverName = "AccessTokenOpenIDRelyingParty"
	userDir = "../access-token-rp-wlpcfg"

	install {
		licenseCode = "${projectLicenseCode}"
		version = "16.0.0_04"
		baseDir = "${libertyBaseDir}"
	}

	packageLiberty {
		include = "usr"
		archive = "build/libs/AccessTokenRPApp.zip"
	}

	features {
		name = ["servlet-3.1","jsp-2.3","openidconnectclient-1.0","openidconnectserver-1.0"]
		acceptLicense = true
		whenFileExists = "ignore"
	}
}
```

Here is the output of the logs:

```
Execution failed for task ':access-token-rp-application:installFeature'.
> CWWKM2002E: Failed to invoke [/Users/ernani/Downloads/sample.microservices.security/liberty.runtime/wlp/bin/installUtility, install, --acceptLicense, servlet-3.1,jsp-2.3,openidconnectclient-1.0,openidconnectserver-1.0]. RC= 21 but expected=[0, 22].
```

According to the error code, the installUtility page at https://www.ibm.com/support/knowledgecenter/SSD28V_9.0.0/com.ibm.websphere.wlp.core.doc/ae/rwlp_command_installutility.html

Lists the following potential issues:

A runtime exception occurred because of one or more of the following conditions:
- A runtime exception occurred during the installation of the .esa subsystem archive file.
- A license is not accepted or acknowledged.
- The .esa subsystem archive file did not extract correctly.

Is this build bugged?

Can someone help? Thanks a lot in advance.

**Comment by ernani** [comment]
FYI, the same errors happens when I try a different distro, aka, `webProfile7`

```
liberty {
	installDir = "${libertyBaseDir}/wlp"
	serverName = 'AccessTokenOpenIDRelyingParty'
	userDir = '../access-token-rp-wlpcfg'

	install {
		licenseCode = "${projectLicenseCode}"
		version = '16.0.0_04'
		baseDir = "${libertyBaseDir}"
		type = 'webProfile7'
	}

	packageLiberty {
		include = 'usr'
		archive = 'build/libs/AccessTokenRPApp.zip'
	}

	features {
		name = ['servlet-3.1','jsp-2.3','openidconnectclient-1.0','openidconnectserver-1.0']
		acceptLicense = true
		whenFileExists = 'ignore'
	}
}
```

Thanks!

**Comment by hughesj** [comment]
@ernani the error is caused by WASdev/ci.ant#71

**Comment by ernani** [comment]
Thanks! Yes, I've been following it up with Ozzy which has been of very great help! Thanks, I am following it up there as well!
